name:                yesod-autoreload
version:             0.0.0.0
github:              "NorfairKing/yesod-autoreload"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - shakespeare
  - text
  - yesod-core
  - yesod-websockets

executables:
  yesod-autoreload-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-autoreload
    - yesod-core

tests:
  yesod-autoreload-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-autoreload
